logging:
  level:
    ROOT: ERROR
    io.reactivestax: DEBUG
    #org.springframework: ERROR
    #org.springframework.boot.context.config: DEBUG
    #org.springframework.data: DEBUG
    #org.springframework.ws.client.MessageTracing.sent: TRACE
    #org.springframework.ws.client.MessageTracing.received: TRACE
    #org.springframework.ws.server.MessageTracing.sent: TRACE
    #org.springframework.ws.server.MessageTracing.received: TRACE
    #org.apache.http.headers: TRACE
    #org.apache.http: TRACE
    #org.apache.http.wire: TRACE
    #org.apache.wss4j: TRACE
pattern:
  console: "%d %-5level %logger : %msg%n"

api:
  title: "Full Stack Labs Inc"
  description: "Full Stack Labs Inc"
  version: 1.0
  terms-of-service-url: "Full Stack Labs terms and conditions"
  contact: "brij@fullstacklabs.ca"
  email: brij@fullstacklabs.ca
  url: https://www.fullstacklabs.ca
  license: "Full Stack Labs API License"
  license-url: https://www.fullstacklabs.ca
  
activemq:
  broker-url: tcp://localhost:61616
  #broker-url: tcp://localhost:5672

destination:
  input-queue: input-queue
  output-queue: output-queue


#spring.datasource:
#  url: jdbc:mysql://localhost:3306/profilemgmt?serverTimezone=EST5EDT&useSSL=false
#  username: root
#  password: bootcamp
  
spring.dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:profilemgmt}?serverTimezone=EST5EDT&allowPublicKeyRetrieval=true&useSSL=false
  username: ${MYSQL_USER:root}
  password: ${MYSQL_PASSWORD:bootcamp}


management.endpoints:
  # disable beans endpoint
  beans.enabled: true
  # expose all endpoints:
  web.exposure.include: "*"


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
# jackson:
#    property-naming-strategy: KEBAB_CASE

